### ISSUE TITLE
Splitting Reciever

### ISSUE THREAD

**Issue by timmit99** [Ansuzalgiz/SABR#1]
What printer are you printing this on? At almost 500mm in length the receiver would need to be cut down into 2-3 pieces to be manageable for most standard printers (200mm-220mm).  Even my Wilson 2 at 200x300x200 would need to do this in two parts. What software was used to design this? I would be willing to work on splitting this file p if i could get the source files to make this easier on the average person. 

Thanks,

**Comment by Ansuzalgiz** [comment]
Pull request for splitting large parts has been merged.
